In [2]:
import numpy as np

In [3]:
#creating array with a(advanced)range function of numpy
a = np.arange(15)   # single dimensional
a = np.arange(15).reshape(3, 5)  #multidimensional array

In [3]:
a.size   # size of array

15

In [6]:
a.ndim  # dimension of array

2

In [7]:
a.dtype  # datatype of array

dtype('int32')

In [8]:
a.shape

(3, 5)

In [10]:
list_b = [1,2,3,4,5,6,7,8,9]                 #creating array from iterator
b = np.array(list_b).reshape(3,3)

In [11]:
b = np.array([(1.5,2,3), (4,5,6)])          # creating multi dimensional array from iterator

In [12]:
c = np.array( [ [1,2], [3,4] ],dtype=complex)      # dtype can be specified

In [14]:
zeros = np.zeros((3,4))            # array of zeros

In [18]:
ones = np.ones(  (2,3,4), dtype=np.int16)    # array of ones

In [16]:
cd = np.arange(0,2,0.3)                      # custom range

In [19]:
np.linspace(0,2,9)                   # getting req no of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
A = np.array(  [[1,1], [0,1]]  )
B = np.array(  [[2,0], [3,4]]  )
prod1 = A * B   # ELEMENTWISE PRODUCT

prod2 = A @ B   #MATRIX PRODUCT
prod3 = A.dot(B)  # ANOTHER  MATRIX PRODUCT

In [41]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3                # multiplies to each element
b += a                   # adds to each element
a = np.random.random((2,3))
a.sum()
a.min()
a.max()


0.7462232055845638

In [4]:
a = np.array( [20,30,40,50]  )
b = np.arange( 4 )
c = a-b

b**2
10*np.sin(a)
a<35

array([ True,  True, False, False])

In [13]:
rand_arr = np.random.randint(1, 10, (4, 5) )
rand_arr.sum()

105

In [12]:
rand_arr.max()


9

In [11]:

rand_arr.min()

1

In [38]:
arr3 = np.random.random((4,5))*100

In [16]:
rand_arr*10

array([[20, 60, 10, 40, 70],
       [10, 90, 90, 80, 50],
       [20, 50, 60, 50, 50],
       [50, 60, 40, 60, 90]])

In [19]:
arr1 = np.array( [20,30,40,50]  )
arr1 = np.arange(11,20).reshape(3,3)

In [20]:
arr1[1]

array([14, 15, 16])

In [21]:
arr1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [22]:
arr1[1,2]

16

In [23]:
arr1[0,:]

array([11, 12, 13])

In [24]:
arr1[:,0]

array([11, 14, 17])

In [25]:
arr2 = np.arange(1,21).reshape(4,5)

In [27]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
arr2[3,3]

19

In [30]:
arr2[2,3:5]

array([14, 15])

In [35]:
arr2[1:4,1]

array([ 7, 12, 17])

In [36]:
arr2.diagonal()

array([ 1,  7, 13, 19])

In [39]:
np.floor(rand_arr)

array([[2., 6., 1., 4., 7.],
       [1., 9., 9., 8., 5.],
       [2., 5., 6., 5., 5.],
       [5., 6., 4., 6., 9.]])

# stacking vertically - no. of columns should be same


In [42]:
arr4 = np.arange(1,7).reshape(2,3)
arr5 = np.arange(8,14).reshape(2,3)

In [43]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr5

array([[ 8,  9, 10],
       [11, 12, 13]])

In [45]:
np.vstack((arr4, arr5))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [47]:
np.hstack((arr4,arr5))

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

In [48]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.hsplit(arr4, 3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [50]:
np.vsplit(arr4,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [51]:
arr4.T #TRANSPOSE

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
arr4*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [57]:
arr4 * arr5

array([[ 8, 18, 30],
       [44, 60, 78]])

In [58]:
arr4 @ arr5

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [59]:
arr6 = np.arange(1,5).reshape(2,2)

In [60]:
arr6

array([[1, 2],
       [3, 4]])

In [61]:
arr6 @ arr4

array([[ 9, 12, 15],
       [19, 26, 33]])

In [63]:
arr6.dot(arr4)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [65]:
bool_arr = arr2 %  10 ==0

In [66]:
arr2[bool_arr]

array([10, 20])

In [68]:
arr2.trace()  # sum of diagonals

40